name: Builds
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/docs.yaml'
      - '.github/workflows/tests.yaml'
      - '*.md'
  pull_request:
    branches:
      - main

jobs:
  bionic:
    # Bionic default: gcc 7, python 3.6
    name: Bionic
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake .. -DBUILD_PYTHON=ON
          make

  focal:
    # Focal default: gcc 9, python 3.8
    name: Focal
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake .. -DBUILD_PYTHON=ON
          make

  macos:
    # Catalina default: clang 12, python 3.9
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake .. -DBUILD_PYTHON=ON
          make

  ubuntu_pip:
    name: Ubuntu pip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          pip install . -vvv

  ubuntu_pip_dev:
    name: Ubuntu pip dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          pip install -e . -vvv

  macos_pip:
    name: macOS pip
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          pip3 install . -vvv
