name: Docs
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/builds.yaml'
      - ".github/workflows/releases.yaml"
      - ".github/workflows/publish.yaml"
      - '.github/workflows/tests.yaml'
      - '*.md'
  pull_request:
    branches:
      - main

jobs:
  generate_docs:
    name: Generate Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pip dependencies
        run: |
          sudo apt update
          sudo apt install -y doxygen
          pip install pipenv
          pipenv install --dev

      - name: Build
        run: |
          # spatialdyn needs to be in the virtual environment.
          pipenv run pip install -e .
          pipenv run make -C docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
