name: Release
on:
  workflow_run:
    workflows:
      - Builds
    types:
      - completed

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    concurrency: release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
